name: Release

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5.0.0
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v5.5.0
      with:
        cache-dependency-path: go.sum
        go-version-file: go.mod

    - uses: crazy-max/ghaction-import-gpg@v6.3.0
      id: import_gpg
      with:
        gpg_private_key: ${{ secrets.TERRAFORM_REGISTRY_GPG_PRIVATE_KEY }}

    - uses: goreleaser/goreleaser-action@v6.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
      with:
        args: release --clean
        version: latest
